name: 同步上游仓库

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发（每天凌晨3点）
  schedule:
    - cron: '0 3 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: 配置Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/qier222/YesPlayMusic.git
          
      - name: 获取上游更新
        run: |
          git fetch upstream
          
      - name: 同步上游更改
        run: |
          # 保存当前分支名称
          CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
          
          # 创建临时分支
          git checkout -b temp-sync-branch
          
          # 尝试合并上游更改
          if git merge upstream/$CURRENT_BRANCH --no-edit; then
            echo "成功合并上游更改"
            
            # 切回原分支并应用更改
            git checkout $CURRENT_BRANCH
            git merge temp-sync-branch
            
            # 推送到远程
            git push origin $CURRENT_BRANCH
            
            # 删除临时分支
            git branch -D temp-sync-branch
          else
            echo "合并冲突，需要手动解决"
            git merge --abort
            git checkout $CURRENT_BRANCH
            git branch -D temp-sync-branch
            exit 1
          fi
